# Generated by Django 6.1.1 on 2026-10-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name': 'contacto', 'verbose_name_plural': 'contactos'},
        ),
        migrations.AlterModelOptions(
            name='cuenta',
            options={'verbose_name': 'cuenta', 'verbose_name_plural': 'cuentas'},
        ),
        migrations.AlterModelOptions(
            name='moneda',
            options={'verbose_name': 'moneda', 'verbose_name_plural': 'monedas'},
        ),
        migrations.AlterModelOptions(
            name='transaccion',
            options={'ordering': ['-fecha'], 'verbose_name': 'transacción', 'verbose_name_plural': 'transacciones'},
        ),
    ]
