"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os # "os" permite leer variables de entorno del sistema
import dj_database_url  # Convierte una dirección DATABASE_URL (la que entregan Neon y Render) en la configuración de Django
from django.core.exceptions import ImproperlyConfigured  # Error que se lanza cuando falta una configuración obligatoria
from dotenv import load_dotenv  # load_dotenv lee el archivo .env y carga sus valores como variables de entorno

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')   # Carga las variables del archivo .env que está en la raíz del proyecto

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# Estas tres configuraciones cambian entre tu equipo y el servidor, por eso se leen del entorno (archivo .env o panel de Render).
# Si la variable no existe se usa el valor de desarrollo, así el proyecto sigue funcionando en local sin configurar nada.

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG es True solo si la variable DEBUG vale true/1/yes; en Render se define DEBUG=False
DEBUG = os.getenv('DEBUG', 'True').lower() in ('1', 'true', 'yes')

# SECURITY WARNING: keep the secret key used in production secret!
# La clave de desarrollo es pública (está en el repositorio), por eso en producción se exige una propia
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-_6c*g0_9m%x_=7x$ot&s2i=&(*)u=%zll=fc@^mqhu(@ibwlhu')
if not DEBUG and SECRET_KEY.startswith('django-insecure-'):
    raise ImproperlyConfigured('En producción (DEBUG=False) hay que definir la variable de entorno SECRET_KEY.')

# Direcciones desde las que se puede entrar, separadas por coma; ejemplo en Render: .onrender.com (el punto inicial incluye todos los subdominios)
ALLOWED_HOSTS = [host.strip() for host in os.getenv('ALLOWED_HOSTS', '').split(',') if host.strip()]

# Orígenes desde los que se aceptan formularios (protección CSRF); en HTTPS deben incluir el esquema, ejemplo: https://*.onrender.com
CSRF_TRUSTED_ORIGINS = [origen.strip() for origen in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if origen.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gestion',   # Nuestra app; sin esta línea Django no reconoce sus modelos
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise sirve los archivos estáticos (CSS, JS, imágenes) desde la propia aplicación; en Render no hay otro servidor que lo haga
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Exige sesión en todas las pantallas, salvo las marcadas como públicas
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Carpeta templates/ de la raíz del proyecto, donde viven las plantillas compartidas
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases


# Lee del .env qué motor usar; si la variable no existe, usa "sqlite" por defecto
DB_ENGINE = os.getenv('DB_ENGINE', 'sqlite')

# Si existe la variable DATABASE_URL (Render y Neon la entregan), tiene prioridad sobre todo lo demás:
# una sola dirección con usuario, clave, servidor y base de datos
if os.getenv('DATABASE_URL'):
    DATABASES = {
        # conn_max_age mantiene abierta la conexión 10 minutos; conn_health_checks la revisa antes de reutilizarla
        'default': dj_database_url.config(conn_max_age=600, conn_health_checks=True),
    }
# Si en el .env pusimos "postgres", configuramos la conexión a PostgreSQL
elif DB_ENGINE == 'postgres':
    DATABASES = {
        'default': {
            # Le dice a Django que use el adaptador de PostgreSQL (psycopg2)
            'ENGINE': 'django.db.backends.postgresql',
            # Nombre de la base de datos que creamos en el paso 1
            'NAME': os.getenv('DB_NAME'),
            # Usuario de PostgreSQL
            'USER': os.getenv('DB_USER'),
            # Contraseña de ese usuario
            'PASSWORD': os.getenv('DB_PASSWORD'),
            # Dónde corre PostgreSQL (localhost = tu propio equipo)
            'HOST': os.getenv('DB_HOST', 'localhost'),
            # Puerto de PostgreSQL (5432 es el estándar)
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
# En cualquier otro caso, usamos SQLite (un archivo db.sqlite3 en la raíz)
else:
    DATABASES = {
        'default': {
            # Le dice a Django que use el adaptador de SQLite (viene incluido)
            'ENGINE': 'django.db.backends.sqlite3',
            # Ruta del archivo donde SQLite guarda los datos
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

# Idioma del sitio: español de Chile; afecta al panel de administración y a los mensajes de validación
LANGUAGE_CODE = 'es-cl'

# Zona horaria para mostrar las fechas; la base de datos sigue guardando en UTC porque USE_TZ es True
TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True

# Muestra los números con separador de miles según el idioma (es-cl): 115000,00 se ve como 115.000,00
USE_THOUSAND_SEPARATOR = True

# Carpeta con formatos propios (core/formats/es_CL/formats.py): hace que el separador de miles sea el punto y no un espacio
FORMAT_MODULE_PATH = ['core.formats']


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# Carpetas adicionales donde Django busca archivos estáticos, además de las carpetas static/ de cada app
STATICFILES_DIRS = [BASE_DIR / 'static']

# Carpeta a la que collectstatic copia todos los archivos estáticos, para publicarlos en producción
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Cómo se guardan y sirven los estáticos. En producción (DEBUG=False) WhiteNoise los comprime y les pone un código en el nombre
# (estilos.3f2a1b.css), así el navegador descarga la versión nueva cuando cambian. Esa versión necesita haber ejecutado collectstatic,
# por eso en desarrollo (DEBUG=True) se usa el almacenamiento normal.
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage' if DEBUG
        else 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# ---------- Seguridad y registros en producción ----------
if not DEBUG:
    # Render atiende el HTTPS por fuera y le pasa a Django la petición como HTTP; este encabezado le avisa que el original era HTTPS
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True  # Redirige cualquier visita HTTP a HTTPS
    SECURE_REDIRECT_EXEMPT = [r'^salud/$']  # La comprobación de Render entra por HTTP interno y no debe ser redirigida
    SESSION_COOKIE_SECURE = True  # La cookie de sesión solo viaja por HTTPS
    CSRF_COOKIE_SECURE = True  # La cookie del token CSRF solo viaja por HTTPS
    SECURE_HSTS_SECONDS = 3600  # El navegador recordará usar solo HTTPS durante 1 hora (se puede subir cuando todo esté estable)

# Registros: con DEBUG=False Django no muestra los errores en ninguna parte por defecto.
# Esta configuración los envía a la consola, que es lo que Render muestra en la pestaña Logs.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {'consola': {'class': 'logging.StreamHandler'}},
    'root': {'handlers': ['consola'], 'level': 'INFO'},
    'loggers': {
        'django.request': {'handlers': ['consola'], 'level': 'ERROR', 'propagate': False},
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# Autenticación
LOGIN_URL = 'login'# Nombre de la ruta a la que se envía a quien intenta entrar sin sesión
LOGIN_REDIRECT_URL = 'gestion:inicio'# Nombre de la ruta a la que se va después de iniciar sesión
LOGOUT_REDIRECT_URL = 'login'# Nombre de la ruta a la que se va después de cerrar sesión